server:
  port: 8000

spring:
  profiles:
    # ???? dev??
    active: dev
  jackson:
    # ???????????? null, ????
    default-property-inclusion: non_null
    # ????????
    date-format: yyyy-MM-dd HH:mm:ss

# ????
logging:
  config: classpath:logback-weblog.xml
